version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    groups:
      dependencies:
        patterns:
          - '*'
    ignore:
      - dependency-name: 'expo'
      - dependency-name: 'expo-*'
      - dependency-name: '@expo/*'
      - dependency-name: 'react'
      - dependency-name: 'react-native'
      - dependency-name: 'react-native-*'
      - dependency-name: '@react-native/*'
      - dependency-name: 'jest-expo'
      - dependency-name: 'babel-preset-expo'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns:
          - '*'
