#!/usr/bin/env node
const fs = require('node:fs');
const path = require('node:path');

const root = path.join(__dirname, '..');

// Only generated outputs; native projects are regenerated by Expo CNG.
for (const target of ['android', 'ios', '.expo', 'dist', 'coverage']) {
  fs.rmSync(path.join(root, target), { recursive: true, force: true });
}
